[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optimizers"
version = "0.2.0"
description = "A collection of optimization algorithms (GA, PSO, ACO, GD, etc.)"
authors = [ { name = "fundthmcalculus" } ]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
keywords = ["optimization", "GA", "PSO", "ACO", "GD"]
dependencies = [
	"numpy>=1.21",
    "plotly>=6.0.0",
    "tqdm>=4.60",
    "joblib>=1.0",
    "contextlib2>=0.6.0",
    "kmodes>=0.12.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.16",
]

[project.optional-dependencies]
dev = [
	"pytest>=6.0",
	"black>=24.0",
    "matplotlib>=3.10",
    "flake8",
    "Flake8-pyproject",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"] # <-- this changed

[project.scripts]
optimizers = "optimizers.__init__:main"

[tool.flake8]
max-line-length = 120
exclude = ".git,__pycache__,build,dist,.eggs,.tox,.venv,venv"
include = "./src,./tests"
extend-ignore = ["E203"]
